version: "3.8"
services:

  db:
    image: postgres
    container_name: "local_postgres"
    ports:
    - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: trademate


  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: "trading_assistant_api"
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/trademate
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    restart: always